name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: Manual   
        required: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Build and Generate Package # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build    
      - run: cd .next; zip -r ../deploy.zip .
        env:
            CI: true
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: winvinaya-app
          environment_name: winvinaya-dev
          existing_bucket_name: elasticbeanstalk-us-east-1-988347388587
          version_label: 1
          region: us-east-1
          deployment_package: deploy.zip
        
